---
# defaults file for prometheus-node-exporter
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_arch: amd64
node_exporter_version: 1.1.2
node_exporter_proxy_port: 8080
node_exporter_custom_metrics_folder: /var/lib/node_exporter/textfile_collector
domain: example.com
nginx_auth_user: metrics
nginx_auth_passw: S0mePassw0rd
